name: 'Submit LAVA job'
description: 'Greet someone and record the time'
inputs:
  job_definition:
    description: 'Test job definition to submit'
    required: true
  lava_token:
    description: 'Authentication token for job submission'
    required: true
  lava_url:
    description: 'URL of LAVA instance'
    required: true
outputs:
  job-id:
    description: 'Stringified version of job ID list'
runs:
  #  using: 'docker'
  #  image: 'Dockerfile'
  using: 'node20'
  main: 'submit.js'
