on: [workflow_dispatch]

jobs:
  submit_lava_job:
    runs-on: ubuntu-latest
    name: submit lava job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: show
        run: "ls -la"
      - name: submit
        uses: mwasilew/lava-action@v11
        with:
          lava_token: ${{ secrets.LAVA_TOKEN }}
          lava_url: "lava.infra.foundries.io"
          job_definition: "lava.yaml"

