on: [workflow_dispatch]

jobs:
  submit_lava_job:
    runs-on: ubuntu-latest
    name: submit lava job
    steps:
      - name: submit
        uses: mwasilew/lava-action@v3
        with:
          lava-token: ${{ secrets.LAVA_TOKEN }}
          lava-url: "https://lava.infra.foundries.io"
          job-definition: "lava.yaml"

