on: [workflow_dispatch]

jobs:
  submit_lava_job:
    runs-on: ubuntu-latest
    name: submit lava job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: show
        run: "ls -la"
      - name: submit
        uses: mwasilew/lava-action@v9
        with:
          lava-token: ${{ secrets.LAVA_TOKEN }}
          lava-url: "lava.infra.foundries.io"
          job-definition: "lava.yaml"

